$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: FecUnzipPipeline
description: Pipeline to extract data and merge it all the way to delta


settings:
  default_compute: azureml:smallStandard

outputs:
  fec_file_temp:
    mode: rw_mount

jobs:
  fec_unzip:
    type: command
    component: azureml:fec_unzip@latest
    inputs:
      run_date: 20221101
      metadata_dataset:
        type: uri_file
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/fecmetadata/paths/rawparserdata.json
    outputs:
      unzipped_fec_files: ${{parent.outputs.fec_file_temp}}
  delta_merge:
    type: command
    component: azureml:fec_delta_merge@latest
    inputs:
      unzipped_fec_files: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
