$schema: https://azuremlschemas.azureedge.net/latest/pipelineJob.schema.json
type: pipeline

display_name: FecUnzipPipeline
description: Pipeline to extract data and merge it all the way to delta


settings:
  default_compute: azureml:smallStandard

inputs:
  run_date: latest  # 20220227 as example

outputs:
  # Must have this output listed here or you must specify a path for it. I'm considering switching to an explicit path.
  fec_file_temp:
    mode: rw_mount

jobs:
  fec_unzip:
    type: command
    component: azureml:fec_unzip@latest
    inputs:
      run_date: ${{parent.inputs.run_date}}
      metadata_dataset:
        type: uri_file
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/fecmetadata/paths/rawparserdata.json
    outputs:
      unzipped_fec_files: ${{parent.outputs.fec_file_temp}}
  delta_merge_forms:
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_forms.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --delta_uri ${{outputs.delta_uri}}
  delta_merge_sa:
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_sa.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
      forms_done_gate:
        path: ${{parent.jobs.delta_merge_forms.outputs.delta_uri}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --forms_done_gate ${{inputs.forms_done_gate}}
       --delta_uri ${{outputs.delta_uri}}
  delta_merge_sb:
    # https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=cli
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_sb.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
      forms_done_gate:
        path: ${{parent.jobs.delta_merge_forms.outputs.delta_uri}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --forms_done_gate ${{inputs.forms_done_gate}}
       --delta_uri ${{outputs.delta_uri}}
  delta_merge_sc:
    # https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=cli
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_sc.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
      forms_done_gate:
        path: ${{parent.jobs.delta_merge_forms.outputs.delta_uri}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --forms_done_gate ${{inputs.forms_done_gate}}
       --delta_uri ${{outputs.delta_uri}}
  delta_merge_sd:
    # https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=cli
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_sd.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
      forms_done_gate:
        path: ${{parent.jobs.delta_merge_forms.outputs.delta_uri}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --forms_done_gate ${{inputs.forms_done_gate}}
       --delta_uri ${{outputs.delta_uri}}
  delta_merge_sh:
    # https://learn.microsoft.com/en-us/azure/machine-learning/how-to-submit-spark-jobs?tabs=cli
    type: spark
    compute: azureml:smallTestSpark
    conf:
      spark.executor.instances: "1"
      spark.driver.memory: "1g"
      spark.driver.cores: "2"
      spark.executor.memory: "4g"
      spark.executor.cores: "2"
    code: "./deltaMergeComponent"
    entry:
      file: "merge_sh.py"
    inputs:
      unzipped_fec_files: 
        path: ${{parent.jobs.fec_unzip.outputs.unzipped_fec_files}}
        type: uri_folder
        mode: direct
      forms_done_gate:
        path: ${{parent.jobs.delta_merge_forms.outputs.delta_uri}}
        type: uri_folder
        mode: direct
    outputs:
      delta_uri:
        type: uri_folder
        mode: direct
        path: azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/tables
    args: >-
       --unzipped_fec_files ${{inputs.unzipped_fec_files}} 
       --forms_done_gate ${{inputs.forms_done_gate}}
       --delta_uri ${{outputs.delta_uri}}
  write_status:
    type: command
    code: "./statusUpdates"
    environment: azureml:base-plus-fecpipeline@latest
    command: "python write_complete.py --run_date ${{inputs.run_date}} --sa_status ${{inputs.sa_status}} --sb_status ${{inputs.sb_status}} --sc_status ${{inputs.sc_status}} --sd_status ${{inputs.sd_status}} --sh_status ${{inputs.sh_status}}"
    inputs:
      run_date: ${{parent.inputs.run_date}}
      sa_status:
        type: uri_folder
        path: ${{parent.jobs.delta_merge_sa.outputs.delta_uri}}
      sb_status:
        type: uri_folder
        path: ${{parent.jobs.delta_merge_sb.outputs.delta_uri}}
      sc_status:
        type: uri_folder
        path: ${{parent.jobs.delta_merge_sc.outputs.delta_uri}}
      sd_status:
        type: uri_folder
        path: ${{parent.jobs.delta_merge_sd.outputs.delta_uri}}
      sh_status:
        type: uri_folder
        path: ${{parent.jobs.delta_merge_sh.outputs.delta_uri}}
    outputs:
      status_out_path: 
        mode: rw_mount
        path: "azureml://subscriptions/f48a2553-c966-4d06-8faa-c5096da10254/resourcegroups/rg-fecdata/workspaces/fecaml/datastores/merged_fec_data/paths/status"
